# Generated by Django 3.2.7 on 2021-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_auto_20211002_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='adress',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cnp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
